global:
   resolve_timeout: 2m # 未收到標記告警通知，等待 timeout 時間之後事件標記為 resolve。
# 所有 alert 資訊進入後的 root，用來設定 alert 的 route 策略
route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 10s # 重複發送告警的間隔時間
  repeat_interval: 1h
  receiver: 'slack-receiver'
  routes:
    - receiver: email        
      group_wait: 10s        
      match:
        team: node    

receivers:
  - name: 'slack-receiver'
    slack_configs:
      - api_url: "YOUR_SLACK_WEBHOOK_URL"
        channel: "#alert-test"
        text: "<!channel> \n summary: {{ .CommonAnnotations.summary }}\n description: {{ .CommonAnnotations.description }}"
    # email_configs:
    #   to:
    #   from:
    #   smarthost:
